# Generated by Django 4.1.3 on 2022-11-10 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image_article_is_published_article_likes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Myself',
            new_name='Owner',
        ),
    ]
